### PR TITLE
Allow configuring the encryption parameters

### PR DESCRIPTION
**Pull request by rzane**
This allows configuring the connection's encryption.

## Description

This just adds two extra flags to the connection string.

## Motivation and Context
Some people like encryption.

## How Has This Been Tested?
I ran the tests. I also wrote a new test that checks that the current connection has encryption.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shdblowers** [comment]
Hello, @rzane! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/findmypast-oss/mssqlex/pulls/18). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by rzane** [comment]
hey @shdblowers, I'm pretty sure the CI failure isn't because if this PR.

**Comment by shdblowers** [comment]
Hi, thanks for the PR. Not quite sure what the problem is here, we were having some issues with our CI previously due to Microsoft keep swapping between versions 13 and 17 of the driver, but it is installing the expected version. Just seems to be installing in an unexpected location

**Comment by shdblowers** [comment]
@rzane rebasing/merge master on this branch should make it pass now :smile:

**Comment by rzane** [comment]
Okay, I just rebased. Would you be able to cut a release after this gets merged? It would really help me out.

**Comment by shdblowers** [comment]
Sure

**Comment by shdblowers** [comment]
`1.1.0` is 🚀

**Comment by rzane** [comment]
👏

**Pull request merged**
