### PR TITLE
Experimental Sybase support

### PR DESCRIPTION
**Pull request by kizzx2**

### CODE REVIEW

**Comment by shdblowers** [comment]
Hello, @kizzx2! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/findmypast-oss/mssqlex/pulls/3). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by jbachhardie** [comment]
Thanks for the PR.

I'd say this seems like an entirely reasonable addition, but I'd like to see the integration test suite ran against Sybase before we advertise support for it. Sybase could be run in a container just like MS SQL Server is currently and tested against on Travis.

**Comment by jbachhardie** [comment]
Another thing, if you could add the ability to specify extra connection string parameters like `TDS_Version` as, say, a map that gets converted in `Protocol.connect/1` that would be better than hacking that in by appending it to the end of `hostname`.

**Comment by kizzx2** [comment]
@jbachhardie Sure, I am trying to use `mssqlex` in my work with a production Sybase and would try to clean up this PR when I get the time, along with some other things that I discover along the way.

Regarding the option for "advanced options" like `TDS_Version`, given the [plethora of options](http://www.freetds.org/userguide/odbcconnattr.htm) one can actually add, and the norm of specifying a connection string when using ODBC how about just add a `connection_string` parameter that overrides other options when it's present? Probably easier than adding an option for each of them.

**Comment by jbachhardie** [comment]
We could have an `additional_options` parameter that takes a map, i.e. `%{"TDS_Version" => "5.0", "TextSize" => 2000, ...}` which gets parsed into connection string parameters and appended at the end of the other parameters. That way people can use the standard params and extra ones at the same time, and it can all be expressed in native Elixir syntax rather than connection string syntax.

**Comment by kizzx2** [comment]
Just wanted to check in, We switched over to use [erlangbureau/jamdb_sybase](https://github.com/erlangbureau/jamdb_sybase) instead, due to a fatal [hardcoded constraint](https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/lib/odbc/c_src/odbcserver.h#L25) in Erlang's ODBC implementation.

Basically, Erlang ODBC will silently truncate any value fields that's longer than 8KB. That became a deal breaker for us.

I am not sure whether this issue can be circumvented when dealing with MSSQL, but we wasted enough time fighting with it for our Sybase project.

I can finish this PR for the options part but probably will not be able to invest the time needed to get test coverage and fix all the test cases.

What do you think?

**Comment by shdblowers** [comment]
Hi @kizzx2 sorry for not getting back sooner.

The options functionality sounds like a worthwhile addition, if you're willing to code it, we're willing to review/accept it.

However, we won't accept the sybase support code without proper test coverage.

**Comment by shdblowers** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
